/**
 * formatter.ts — Builds the Markdown body for a GitHub PR comment.
 *
 * The comment is structured as:
 *   ## CodeCheck Results
 *   > N files · X passed · Y failed · Z% pass rate
 *
 *   ### ✅ functionName (`src/utils.ts`)
 *   | Test | Type | Duration |
 *   | ✓ description | unit | 12ms |
 *   ...
 *
 *   ### ❌ otherFunction (`src/utils.ts`)
 *   ...
 *   <details><summary>Failures</summary>...</details>
 */

import type { TestResult, CodeCheckConfig } from '@codecheck/core'

export function buildCommentBody(results: TestResult[], config: CodeCheckConfig): string {
  if (results.length === 0) {
    return '## CodeCheck Results\n\nNo testable targets found in the changed files.'
  }

  const total = results.length
  const passed = results.filter((r) => r.passed).length
  const failed = total - passed
  const rate = Math.round((passed / total) * 100)
  const aboveThreshold = rate >= config.threshold * 100
  const cached = results.filter((r) => r.fromCache).length

  const statusEmoji = aboveThreshold ? '✅' : '❌'
  const rateStr = `${rate}%`
  const cachedNote = cached > 0 ? ` · ${cached} from cache` : ''

  const lines: string[] = [
    `## ${statusEmoji} CodeCheck Results`,
    ``,
    `> **${passed} passed** · **${failed} failed** · **${rateStr} pass rate**${cachedNote}`,
    `> Threshold: ${Math.round(config.threshold * 100)}%`,
    ``,
  ]

  // Group by target
  const byTarget = new Map<string, TestResult[]>()
  for (const result of results) {
    const key = `${result.target.filePath}::${result.target.name}`
    const existing = byTarget.get(key)
    if (existing) {
      existing.push(result)
    } else {
      byTarget.set(key, [result])
    }
  }

  for (const [, targetResults] of byTarget) {
    const first = targetResults[0]
    if (!first) continue

    const allPassed = targetResults.every((r) => r.passed)
    const icon = allPassed ? '✅' : '❌'
    const shortPath = first.target.filePath.split('/').slice(-2).join('/')

    lines.push(`### ${icon} \`${first.target.name}\` (${shortPath})`)
    lines.push(``)
    lines.push(`| Status | Test | Type | Duration |`)
    lines.push(`|--------|------|------|----------|`)

    for (const r of targetResults) {
      const status = r.passed ? '✓' : '✗'
      const dur = `${r.duration}ms`
      const cached = r.fromCache ? ' *(cached)*' : ''
      lines.push(`| ${status} | ${r.testCase.description}${cached} | \`${r.testCase.testType}\` | ${dur} |`)
    }

    const failures = targetResults.filter((r) => !r.passed)
    if (failures.length > 0) {
      lines.push(``)
      lines.push(`<details><summary>Failure details (${failures.length})</summary>`)
      lines.push(``)
      lines.push('```')
      for (const f of failures) {
        lines.push(`✗ ${f.testCase.description}`)
        if (f.error) {
          lines.push(f.error.split('\n').slice(0, 5).join('\n'))
        }
        lines.push(``)
      }
      lines.push('```')
      lines.push(`</details>`)
    }

    lines.push(``)
  }

  if (!aboveThreshold) {
    lines.push(`---`)
    lines.push(`> ⚠️ Pass rate ${rateStr} is below the configured threshold of ${Math.round(config.threshold * 100)}%.`)
  }

  lines.push(``)
  lines.push(`*Generated by [CodeCheck](https://github.com/medhavee/codecheck)*`)

  return lines.join('\n')
}
