/**
 * generator/jest.ts — Converts TestCase[] + TestTarget into a runnable Jest test file.
 *
 * Generated files are written to <cwd>/.codecheck-tmp/ and deleted after the
 * test run (unless keepGeneratedTests is true).
 *
 * Input conventions (set by the LLM prompt):
 *   - No params:          input = null    → fn()
 *   - Single param:       input = value   → fn(value)
 *   - Multiple params:    input = array   → fn(...array)
 */

import crypto from 'node:crypto'
import path from 'node:path'
import type { GeneratedTestFile, TestCase, TestTarget } from '../types.js'

// ─── Public Entry Point ───────────────────────────────────────────────────────

export function generateJestFile(
  target: TestTarget,
  testCases: TestCase[],
  cwd: string
): GeneratedTestFile {
  const content = buildFileContent(target, testCases, cwd)

  const hash = crypto
    .createHash('sha256')
    .update(target.code + JSON.stringify(testCases))
    .digest('hex')
    .slice(0, 8)

  const tmpDir = path.join(cwd, '.codecheck-tmp')
  const filePath = path.join(tmpDir, `${sanitizeName(target.name)}-${hash}.test.ts`)

  return { filePath, content, framework: 'jest', target, testCases }
}

// ─── File Content Builder ─────────────────────────────────────────────────────

function buildFileContent(target: TestTarget, testCases: TestCase[], cwd: string): string {
  const importPath = resolveImportPath(target.filePath, cwd)
  const importLine = `import { ${target.name} } from '${importPath}'`

  const testBlocks = testCases
    .map((tc) => buildTestBlock(tc, target))
    .join('\n\n')

  return [
    `// @ts-nocheck — auto-generated by CodeCheck, type checking intentionally disabled`,
    `// Target: ${target.name} (${target.targetType})`,
    `// Source: ${target.filePath}`,
    ``,
    importLine,
    ``,
    `describe('${target.name}', () => {`,
    testBlocks,
    `})`,
    ``,
  ].join('\n')
}

// ─── Test Block Builder ───────────────────────────────────────────────────────

function buildTestBlock(tc: TestCase, target: TestTarget): string {
  const isAsync = target.isAsync === true
  const asyncKw = isAsync ? 'async ' : ''
  const indent = '  '

  if (tc.shouldThrow === true) {
    return buildThrowBlock(tc, target, asyncKw, indent)
  }
  return buildAssertBlock(tc, target, asyncKw, indent)
}

function buildAssertBlock(
  tc: TestCase,
  target: TestTarget,
  asyncKw: string,
  indent: string
): string {
  const call = buildCall(target, tc.input)
  const expected = serialize(tc.expectedOutput)

  let assertion: string
  if (target.isAsync === true) {
    assertion = `await expect(${call}).resolves.toEqual(${expected})`
  } else {
    assertion = `expect(${call}).toEqual(${expected})`
  }

  return [
    `${indent}it('${escapeSingleQuote(tc.description)}', ${asyncKw}() => {`,
    `${indent}  ${assertion}`,
    `${indent}})`,
  ].join('\n')
}

function buildThrowBlock(
  tc: TestCase,
  target: TestTarget,
  asyncKw: string,
  indent: string
): string {
  const call = buildCall(target, tc.input)
  const errorArg = tc.expectedError != null ? `'${escapeSingleQuote(tc.expectedError)}'` : ''

  let assertion: string
  if (target.isAsync === true) {
    assertion = errorArg !== ''
      ? `await expect(${call}).rejects.toThrow(${errorArg})`
      : `await expect(${call}).rejects.toThrow()`
  } else {
    assertion = errorArg !== ''
      ? `expect(() => ${call}).toThrow(${errorArg})`
      : `expect(() => ${call}).toThrow()`
  }

  return [
    `${indent}it('${escapeSingleQuote(tc.description)}', ${asyncKw}() => {`,
    `${indent}  ${assertion}`,
    `${indent}})`,
  ].join('\n')
}

// ─── Call Builder ─────────────────────────────────────────────────────────────

/**
 * Build the function call expression for the test assertion.
 *
 * Convention (matches what we instruct the LLM to produce):
 *   - null input              → fn()
 *   - single-param function   → fn(input)
 *   - multi-param function    → fn(...input)  where input is an array
 */
function buildCall(target: TestTarget, input: unknown): string {
  const name = target.name
  const paramCount = target.params?.length ?? 0

  if (input === null || input === undefined) {
    return `${name}()`
  }

  if (Array.isArray(input) && paramCount > 1) {
    // Spread array elements as individual arguments
    const args = (input as unknown[]).map(serialize).join(', ')
    return `${name}(${args})`
  }

  return `${name}(${serialize(input)})`
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Compute a relative import path from the .codecheck-tmp/ dir to the source file.
 * Strips the file extension so ts-jest can resolve the TypeScript source.
 */
function resolveImportPath(sourceFilePath: string, cwd: string): string {
  const tmpDir = path.join(cwd, '.codecheck-tmp')
  const ext = path.extname(sourceFilePath)
  const sourceNoExt = sourceFilePath.slice(0, sourceFilePath.length - ext.length)
  const rel = path.relative(tmpDir, sourceNoExt).replace(/\\/g, '/')
  return rel.startsWith('.') ? rel : `./${rel}`
}

/** Serialize a value to its JavaScript source representation */
function serialize(value: unknown): string {
  if (value === undefined) return 'undefined'
  if (Number.isNaN(value as number)) return 'NaN'
  return JSON.stringify(value, null, value !== null && typeof value === 'object' ? 2 : 0) ?? 'null'
}

/** Replace ' with \' inside a string used as a JS string literal */
function escapeSingleQuote(s: string): string {
  return s.replace(/'/g, "\\'")
}

/** Make a target name safe for use in a filename */
function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 40)
}
