/**
 * generator/pytest.ts — Converts TestCase[] + TestTarget into a runnable pytest test file.
 *
 * Generated files are written to <cwd>/.codecheck-tmp/ and deleted after the
 * test run (unless keepGeneratedTests is true).
 *
 * Test function naming convention:
 *   test_{index}_{sanitized_description}
 *
 * This allows the runner to map results back to TestCase[] by index,
 * without relying on lossy description → function name round-tripping.
 *
 * Input conventions (same as jest.ts — set by the LLM prompt):
 *   - No params:          input = null    → fn()
 *   - Single param:       input = value   → fn(value)
 *   - Multiple params:    input = array   → fn(*array elements)
 */

import crypto from 'node:crypto'
import path from 'node:path'
import type { GeneratedTestFile, TestCase, TestTarget } from '../types.js'

// ─── Public Entry Point ───────────────────────────────────────────────────────

export function generatePytestFile(
  target: TestTarget,
  testCases: TestCase[],
  cwd: string,
): GeneratedTestFile {
  const content = buildFileContent(target, testCases, cwd)

  const hash = crypto
    .createHash('sha256')
    .update(target.code + JSON.stringify(testCases))
    .digest('hex')
    .slice(0, 8)

  const tmpDir = path.join(cwd, '.codecheck-tmp')
  const filePath = path.join(tmpDir, `test_${sanitizeName(target.name)}_${hash}.py`)

  return { filePath, content, framework: 'pytest', target, testCases }
}

// ─── File Content Builder ─────────────────────────────────────────────────────

function buildFileContent(target: TestTarget, testCases: TestCase[], cwd: string): string {
  const modulePath = resolveModulePath(target.filePath, cwd)

  // Separate setup cases from regular test cases
  const beforeEachCases = testCases.filter((tc) => tc.category === 'before-each')
  const regularCases = testCases.filter((tc) => tc.category !== 'before-each')

  const headerLines = [
    `# auto-generated by CodeCheck — do not edit`,
    `# Target: ${target.name} (${target.targetType})`,
    `# Source: ${target.filePath}`,
    `# type: ignore`,
    ``,
    `import sys as _sys`,
    `import pytest`,
    ``,
    `_sys.path.insert(0, ${JSON.stringify(cwd)})`,
    ``,
    `from ${modulePath} import ${target.name}`,
    ``,
  ]

  const fixtureLines: string[] = []
  if (beforeEachCases.length > 0) {
    const resetStatements = beforeEachCases.map((tc) => `    ${tc.description}`).join('\n')
    fixtureLines.push(
      `@pytest.fixture(autouse=True)`,
      `def _reset_state():`,
      resetStatements,
      `    yield`,
      ``,
      ``,
    )
  }

  const testFunctions = regularCases
    .map((tc, idx) => buildTestFunction(tc, target, idx))
    .join('\n\n')

  return [...headerLines, ...fixtureLines, testFunctions, ``].join('\n')
}

// ─── Test Function Builder ────────────────────────────────────────────────────

function buildTestFunction(tc: TestCase, target: TestTarget, idx: number): string {
  const fnName = `test_${idx}_${sanitizeName(tc.description)}`
  const isAsync = target.isAsync === true

  if (tc.shouldThrow === true) {
    return buildRaisesFunction(tc, target, fnName, isAsync)
  }
  return buildAssertFunction(tc, target, fnName, isAsync)
}

function buildAssertFunction(
  tc: TestCase,
  target: TestTarget,
  fnName: string,
  isAsync: boolean,
): string {
  const call = buildCall(target, tc.input)
  const isDynamic = tc.expectedOutput === '__dynamic__'

  if (isAsync) {
    if (isDynamic) {
      return [
        `@pytest.mark.asyncio`,
        `async def ${fnName}():`,
        `    result = await ${call}`,
        `    assert result is not None`,
      ].join('\n')
    }
    return [
      `@pytest.mark.asyncio`,
      `async def ${fnName}():`,
      `    result = await ${call}`,
      `    assert result == ${serializePython(tc.expectedOutput)}`,
    ].join('\n')
  }

  if (isDynamic) {
    return [`def ${fnName}():`, `    result = ${call}`, `    assert result is not None`].join('\n')
  }

  return [
    `def ${fnName}():`,
    `    assert ${call} == ${serializePython(tc.expectedOutput)}`,
  ].join('\n')
}

function buildRaisesFunction(
  tc: TestCase,
  target: TestTarget,
  fnName: string,
  isAsync: boolean,
): string {
  const call = buildCall(target, tc.input)
  const errorHint =
    tc.expectedError != null ? `, match=${JSON.stringify(tc.expectedError)}` : ''

  if (isAsync) {
    return [
      `@pytest.mark.asyncio`,
      `async def ${fnName}():`,
      `    with pytest.raises(Exception${errorHint}):`,
      `        await ${call}`,
    ].join('\n')
  }

  return [
    `def ${fnName}():`,
    `    with pytest.raises(Exception${errorHint}):`,
    `        ${call}`,
  ].join('\n')
}

// ─── Call Builder ─────────────────────────────────────────────────────────────

function buildCall(target: TestTarget, input: unknown): string {
  const name = target.name
  const paramCount = target.params?.length ?? 0

  if (input === null || input === undefined) {
    return `${name}()`
  }

  if (Array.isArray(input) && paramCount > 1) {
    const args = (input as unknown[]).map(serializePython).join(', ')
    return `${name}(${args})`
  }

  return `${name}(${serializePython(input)})`
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Compute the Python module path for importing the target.
 * Source: /cwd/src/utils.py → module: src.utils
 * Source: /cwd/utils.py → module: utils
 */
function resolveModulePath(sourceFilePath: string, cwd: string): string {
  const rel = path.relative(cwd, sourceFilePath).replace(/\\/g, '/')
  // Remove .py extension and convert path separators to dots
  const withoutExt = rel.endsWith('.py') ? rel.slice(0, -3) : rel
  return withoutExt.replace(/\//g, '.')
}

/**
 * Serialize a JavaScript value to its Python source representation.
 */
function serializePython(value: unknown): string {
  if (value === null || value === undefined) return 'None'
  if (value === true) return 'True'
  if (value === false) return 'False'
  if (typeof value === 'number') {
    if (Number.isNaN(value)) return 'None'
    if (!Number.isFinite(value)) return 'None'
    return String(value)
  }
  if (typeof value === 'string') {
    // Use repr-style quoting: escape backslashes and single quotes
    const escaped = value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
    return `'${escaped}'`
  }
  if (Array.isArray(value)) {
    return `[${(value as unknown[]).map(serializePython).join(', ')}]`
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `'${k}': ${serializePython(v)}`)
      .join(', ')
    return `{${entries}}`
  }
  return String(value)
}

/** Make a name safe for use in a Python function name or filename */
function sanitizeName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
    .slice(0, 50)
}
