import { describe, it, expect } from 'vitest'
import path from 'node:path'
import { generatePytestFile } from '../generator/pytest.js'
import type { TestCase, TestTarget } from '../types.js'

// ─── Fixtures ─────────────────────────────────────────────────────────────────

const CWD = '/project'

const pyTarget: TestTarget = {
  filePath: '/project/src/math.py',
  name: 'add',
  code: 'def add(a, b):\n    return a + b',
  language: 'python',
  targetType: 'function',
  startLine: 1,
  endLine: 2,
  params: [{ name: 'a' }, { name: 'b' }],
}

const asyncPyTarget: TestTarget = {
  filePath: '/project/src/api.py',
  name: 'fetch_user',
  code: 'async def fetch_user(user_id):\n    return {"name": "Alice"}',
  language: 'python',
  targetType: 'function',
  startLine: 1,
  endLine: 2,
  params: [{ name: 'user_id' }],
  isAsync: true,
}

const happyCase: TestCase = {
  description: 'adds two positive numbers',
  input: [1, 2],
  expectedOutput: 3,
  category: 'happy-path',
  testType: 'unit',
  shouldThrow: false,
}

const throwCase: TestCase = {
  description: 'raises on bad input',
  input: 'bad',
  expectedOutput: null,
  category: 'error-handling',
  testType: 'unit',
  shouldThrow: true,
  expectedError: 'invalid',
}

const dynamicCase: TestCase = {
  description: 'returns dynamic timestamp',
  input: null,
  expectedOutput: '__dynamic__',
  category: 'happy-path',
  testType: 'unit',
  shouldThrow: false,
}

const beforeEachCase: TestCase = {
  description: 'users.clear()',
  input: null,
  expectedOutput: null,
  category: 'before-each',
  testType: 'unit',
  shouldThrow: false,
}

// ─── File Path ────────────────────────────────────────────────────────────────

describe('generatePytestFile — file path', () => {
  it('places test file in .codecheck-tmp/', () => {
    const file = generatePytestFile(pyTarget, [happyCase], CWD)
    expect(file.filePath).toContain('.codecheck-tmp')
  })

  it('produces a .py extension', () => {
    const file = generatePytestFile(pyTarget, [happyCase], CWD)
    expect(file.filePath).toMatch(/\.py$/)
  })

  it('prefixes filename with test_', () => {
    const file = generatePytestFile(pyTarget, [happyCase], CWD)
    expect(path.basename(file.filePath)).toMatch(/^test_/)
  })

  it('sets framework to pytest', () => {
    const file = generatePytestFile(pyTarget, [happyCase], CWD)
    expect(file.framework).toBe('pytest')
  })
})

// ─── File Content — Header ────────────────────────────────────────────────────

describe('generatePytestFile — header', () => {
  it('includes auto-generated comment', () => {
    const file = generatePytestFile(pyTarget, [happyCase], CWD)
    expect(file.content).toContain('auto-generated by CodeCheck')
  })

  it('includes # type: ignore', () => {
    const file = generatePytestFile(pyTarget, [happyCase], CWD)
    expect(file.content).toContain('# type: ignore')
  })

  it('imports pytest', () => {
    const file = generatePytestFile(pyTarget, [happyCase], CWD)
    expect(file.content).toContain('import pytest')
  })

  it('inserts cwd into sys.path', () => {
    const file = generatePytestFile(pyTarget, [happyCase], CWD)
    expect(file.content).toContain('sys.path.insert')
    expect(file.content).toContain(CWD)
  })

  it('imports the function from the correct module path', () => {
    const file = generatePytestFile(pyTarget, [happyCase], CWD)
    // /project/src/math.py → src.math
    expect(file.content).toContain('from src.math import add')
  })
})

// ─── File Content — Test Functions ────────────────────────────────────────────

describe('generatePytestFile — test functions', () => {
  it('generates def test_{N}_{name} functions', () => {
    const file = generatePytestFile(pyTarget, [happyCase], CWD)
    expect(file.content).toContain('def test_0_adds_two_positive_numbers')
  })

  it('generates assert statement for normal tests', () => {
    const file = generatePytestFile(pyTarget, [happyCase], CWD)
    expect(file.content).toContain('assert add(1, 2) == 3')
  })

  it('generates pytest.raises for shouldThrow tests', () => {
    const file = generatePytestFile(pyTarget, [throwCase], CWD)
    expect(file.content).toContain('pytest.raises(Exception')
  })

  it('includes expectedError match in raises', () => {
    const file = generatePytestFile(pyTarget, [throwCase], CWD)
    expect(file.content).toContain('match=')
    expect(file.content).toContain('invalid')
  })
})

// ─── Async Functions ──────────────────────────────────────────────────────────

describe('generatePytestFile — async functions', () => {
  const asyncCase: TestCase = {
    description: 'fetches user data',
    input: '123',
    expectedOutput: { name: 'Alice' },
    category: 'happy-path',
    testType: 'unit',
    shouldThrow: false,
  }

  it('marks async tests with @pytest.mark.asyncio', () => {
    const file = generatePytestFile(asyncPyTarget, [asyncCase], CWD)
    expect(file.content).toContain('@pytest.mark.asyncio')
  })

  it('generates async def test functions', () => {
    const file = generatePytestFile(asyncPyTarget, [asyncCase], CWD)
    expect(file.content).toContain('async def test_')
  })

  it('uses await in async function call', () => {
    const file = generatePytestFile(asyncPyTarget, [asyncCase], CWD)
    expect(file.content).toContain('await fetch_user')
  })
})

// ─── Dynamic and beforeEach ───────────────────────────────────────────────────

describe('generatePytestFile — dynamic outputs and beforeEach', () => {
  it('emits assert result is not None for __dynamic__', () => {
    const file = generatePytestFile(pyTarget, [dynamicCase], CWD)
    expect(file.content).toContain('assert result is not None')
  })

  it('does not emit __dynamic__ literal in output', () => {
    const file = generatePytestFile(pyTarget, [dynamicCase], CWD)
    expect(file.content).not.toContain('__dynamic__')
  })

  it('emits autouse fixture for before-each category', () => {
    const file = generatePytestFile(pyTarget, [beforeEachCase, happyCase], CWD)
    expect(file.content).toContain('@pytest.fixture(autouse=True)')
    expect(file.content).toContain('users.clear()')
  })

  it('does not generate a regular test function for before-each case', () => {
    const file = generatePytestFile(pyTarget, [beforeEachCase, happyCase], CWD)
    expect(file.content).not.toContain('def test_0_users_clear')
  })
})

// ─── Python value serialization ───────────────────────────────────────────────

describe('generatePytestFile — Python serialization', () => {
  it('serializes None for null expectedOutput', () => {
    const noneCase: TestCase = {
      description: 'returns None for missing input',
      input: null,
      expectedOutput: null,
      category: 'edge-case',
      testType: 'unit',
      shouldThrow: false,
    }
    const file = generatePytestFile(pyTarget, [noneCase], CWD)
    expect(file.content).toContain('== None')
  })

  it('serializes True/False for booleans', () => {
    const boolCase: TestCase = {
      description: 'returns True for valid input',
      input: 1,
      expectedOutput: true,
      category: 'happy-path',
      testType: 'unit',
      shouldThrow: false,
    }
    const file = generatePytestFile(pyTarget, [boolCase], CWD)
    expect(file.content).toContain('== True')
  })

  it('serializes strings with single quotes', () => {
    const strCase: TestCase = {
      description: 'returns greeting string',
      input: 'Alice',
      expectedOutput: 'Hello, Alice',
      category: 'happy-path',
      testType: 'unit',
      shouldThrow: false,
    }
    const file = generatePytestFile(pyTarget, [strCase], CWD)
    expect(file.content).toContain("== 'Hello, Alice'")
  })
})
